### ISSUE TITLE
Very unreliable encryption algorithm

### ISSUE THREAD

**Issue by ghost** [JanDotNet/ThinkSharp.Licensing#7]
This library can be used to create and validate license files, which are encrypted files containing the license information. However, the encryption algorithm is very unreliable. Code used for encryption:

```c#
var confusingBytes = new byte[] { 32, 45, 12, 43, 33, 1 };
var bytes = Encoding.UTF8.GetBytes(license);
for (int i = 0; i < bytes.Length; i++)
{
  bytes[i] ^= confusingBytes[i % confusingBytes.Length];
}
return Convert.ToBase64String(bytes);
```

It just "spoils" each byte in the license text. `confusingBytes` are hard-coded! Everyone who knows that this repository was used in an app to manage licenses (it's easy to find out — a hacker just has to look at that app's dependencies) can take these `confusingBytes`, create his own "license" (e.g., expiring in 2030) and encrypt it, so that this library will really think he has a license.

**The encryption algorithm should be updated.**

**Comment by mzayarnyuk** [comment]
protection here must be not lic itself - it must be public and private keys; (when private have only company)

**Comment by mzayarnyuk** [comment]
but additioal manipulations should be added to make of application more complicated; if you use in real commercial product...

**Comment by JanDotNet** [comment]
> [!IMPORTANT]
> Note that the mentioned "encryption" (or confusion) is not part of the actual signing, which prevents hackers form modifing the license!

There are several ways to provide a licence code:

|Mechanism|Implementation affort|Securitization|Possible with ThinkSharp.Licensing|
| ------------- | ------------- | ------------- | ------------- |
|Plain Text|none|none: Licence attributes are visible to the user|Yes|
|BASE64 encoded|very low|Licence attributes are not visible, but can be encoded by anybody with a browser|No|
|confusion like implemented|low|Licence attributes are not visible, but can be encoded by anybody how knows the code|Yes|
|strong encryption|high|Licence attributes are not visible, but can be encoded by anybody how analyses the encryption mechanism. Note that the verification process needs to encode the licence information on client-side, therefore it is not possible to have a 100% secure encryption|No|

Therefore, the implemented "confusion" mechanism was not intended as a higly secure encryption, because the licence attributes are not a secret. However, it would be easy possible to extend the library with a custom encryption extension point, that allows the Issuer to implement it's own encryption. If there is a demand for that feature, feel free to reopen this issue or create a new one.
