### ISSUE TITLE
better separate generatio and verification code....

### ISSUE THREAD

**Issue by mzayarnyuk** [JanDotNet/ThinkSharp.Licensing#8]
I known is opensrc, so hacker will able to find in any way, but:
better separate generation and verification code....
so company will had not only private key but and correct generation code/assambly;

**Comment by JanDotNet** [comment]
Thanks for you feedback. The whole crypto currency eco system (which uses mainly SHA256 instead of SHA512) is based on public known cryptographic secured protocols. Therefore, I think there is no need for hiding generation algorithms.

However, if you want to seperate generation and verification code, you could implement 2 different signers. One with the verification implemenation, that is shipped with the application, and another for signing that is keeped private.
